name = input("Enter your name: ")
age = int(input("Enter your age: "))
color = input("Enter your favorite color: ")
hobby = input("Enter your hobbies: ")
print("\n--- PROFILE ---")
print("Name:",name)
print("Age:",age)
print("Color:",color)
print("Hobbies:",hobby)